#!/bin/bash

#
# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

set -e

help=$1

# if the user wanted to get help for the script
if [[ $help == "--help" ]]
then
  echo "This script issues a 'make clean' in all the projects within the examples/ directory"
  echo "Usage: ./scripts/clean-examples"
  exit 0
fi

# create list of directories to clean
list=$(ls -d examples/emulation/*)
list="$list $(ls -d examples/physical/*)"
current=$(pwd)

# cycle through each directory and clean it
for i in $list
do
  echo "cleaning $i"
  cd $current/$i && make clean && rm -rf .gdb_history
done

echo "done!"
exit 0

